language: cpp
sudo: required
services: docker

git:
  depth: 3
  submodules: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - libcrypto++-dev
    - libcap-dev
    - libkeyutils-dev
    - libncurses5-dev
    - libboost-dev
    - autopoint
    - help2man
    - texinfo

before_script:
  - sudo add-apt-repository -y ppa:sfouladi/protobuf-backports
  - sudo -E add-apt-repository -y 'deb http://ftp.us.debian.org/debian unstable main contrib non-free'
  - sudo apt-get update -qq
  - sudo apt-get install -y --allow-unauthenticated python3.6 protobuf-compiler libprotobuf-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 99
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 99
  - curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
  - sudo pip3.6 install protobuf
  - sudo pip3.6 install boto3

script:
  - ./fetch-toolchain.sh
  - ./autogen.sh
  - ./configure --enable-sanitize
  - make -j3 distcheck V=1 || (cat gg-0.01/_build/src/tests/test-suite.log && exit 1)

notifications:
  slack: keithw:RFEz0IvxWUHbHFan10UNb3Qo
